"""Create core domain models

Revision ID: 4a68b000f588
Revises: 99d002569484
Create Date: 2026-02-06 14:01:56.615396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a68b000f588'
down_revision: Union[str, None] = '99d002569484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the project'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the AI project'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of the project and its purpose'),
    sa.Column('organization', sa.String(length=255), nullable=True, comment='Organization or company owning the project'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_organization'), 'projects', ['organization'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the assessment'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='Project being assessed'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Title or name of this assessment'),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='assessmentstatus', native_enum=False), server_default='draft', nullable=False, comment='Current status of the assessment'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the assessment was completed'),
    sa.Column('risk_level', sa.String(length=50), nullable=True, comment='Overall risk level: unacceptable, high, limited, minimal'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_project_id'), 'assessments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assessments_risk_level'), 'assessments', ['risk_level'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the answer'),
    sa.Column('assessment_id', sa.Integer(), nullable=False, comment='Assessment this answer belongs to'),
    sa.Column('question_id', sa.String(length=100), nullable=False, comment='Identifier of the question being answered'),
    sa.Column('answer_value', sa.JSON(), nullable=True, comment='The answer content (flexible JSON format)'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='Plain text representation of the answer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores user responses to assessment questions'
    )
    op.create_index(op.f('ix_answers_assessment_id'), 'answers', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('regulatory_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Unique identifier for the flag'),
    sa.Column('assessment_id', sa.Integer(), nullable=False, comment='Assessment where this flag was raised'),
    sa.Column('regulation', sa.String(length=100), nullable=False, comment="Which regulation applies (e.g., 'EU_AI_ACT', 'GDPR')"),
    sa.Column('category', sa.String(length=100), nullable=False, comment="Category of the requirement (e.g., 'high_risk_system')"),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='flagseverity', native_enum=False), nullable=False, comment='Severity level of this flag'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short title of the compliance issue'),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed explanation of the requirement or issue'),
    sa.Column('rule_id', sa.String(length=100), nullable=True, comment='Identifier of the rule that raised this flag (for traceability)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was last updated'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_flags_assessment_id'), 'regulatory_flags', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_regulatory_flags_category'), 'regulatory_flags', ['category'], unique=False)
    op.create_index(op.f('ix_regulatory_flags_regulation'), 'regulatory_flags', ['regulation'], unique=False)
    op.create_index(op.f('ix_regulatory_flags_rule_id'), 'regulatory_flags', ['rule_id'], unique=False)
    op.create_index(op.f('ix_regulatory_flags_severity'), 'regulatory_flags', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regulatory_flags_severity'), table_name='regulatory_flags')
    op.drop_index(op.f('ix_regulatory_flags_rule_id'), table_name='regulatory_flags')
    op.drop_index(op.f('ix_regulatory_flags_regulation'), table_name='regulatory_flags')
    op.drop_index(op.f('ix_regulatory_flags_category'), table_name='regulatory_flags')
    op.drop_index(op.f('ix_regulatory_flags_assessment_id'), table_name='regulatory_flags')
    op.drop_table('regulatory_flags')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_assessment_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_risk_level'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_project_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_projects_organization'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
